"""Add api_usage, call_costs, call_recordings tables.

Revision ID: 1a15ed1a5fc5
Revises: 0001
Create Date: 2026-09-16

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "1a15ed1a5fc5"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage',
    sa.Column('call_sid', sa.String(length=100), nullable=True),
    sa.Column('call_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('characters', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_usage_call_sid'), 'api_usage', ['call_sid'], unique=False)
    op.create_index(op.f('ix_api_usage_provider'), 'api_usage', ['provider'], unique=False)
    op.create_table('call_costs',
    sa.Column('call_sid', sa.String(length=100), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=True),
    sa.Column('telephony_cost_usd', sa.Float(), nullable=False),
    sa.Column('openai_cost_usd', sa.Float(), nullable=False),
    sa.Column('voice_cost_usd', sa.Float(), nullable=False),
    sa.Column('email_cost_usd', sa.Float(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_costs_call_sid'), 'call_costs', ['call_sid'], unique=True)
    op.create_table('call_recordings',
    sa.Column('call_sid', sa.String(length=100), nullable=False),
    sa.Column('caller_number', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('audio_file_path', sa.String(length=500), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_recordings_call_sid'), 'call_recordings', ['call_sid'], unique=True)
    op.create_index(op.f('ix_call_recordings_status'), 'call_recordings', ['status'], unique=False)
    # NOTE: autogenerate also flagged `calls.call_sid` / `departments.name` as
    # drift (named UNIQUE CONSTRAINT in 0001 vs UNIQUE INDEX from the ORM's
    # `unique=True`). Both enforce the same invariant — left untouched here to
    # keep this migration scoped to the three missing tables.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_recordings_status'), table_name='call_recordings')
    op.drop_index(op.f('ix_call_recordings_call_sid'), table_name='call_recordings')
    op.drop_table('call_recordings')
    op.drop_index(op.f('ix_call_costs_call_sid'), table_name='call_costs')
    op.drop_table('call_costs')
    op.drop_index(op.f('ix_api_usage_provider'), table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_call_sid'), table_name='api_usage')
    op.drop_table('api_usage')
    # ### end Alembic commands ###
