import type { EditorialPost } from './types'

const images = {
  studio: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=85',
  camera: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=85',
  architecture: 'https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&fit=crop&w=1200&q=85',
  film: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1400&q=85',
  editorial: 'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=1200&q=85',
  portrait: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=85',
}

export const blogPosts: EditorialPost[] = [
  {
    slug: 'why-good-brands-are-easier-to-understand',
    title: 'Why Good Brands Are Easier to Understand',
    excerpt: 'Clarity is not a reduction of ambition. It is what allows a brand’s most valuable ideas to travel further.',
    category: 'Brand Strategy', tags: ['Strategy', 'Branding'], image: images.studio, imageAlt: 'Light-filled creative studio with work tables', author: 'BrandWorks', date: '2026-09-18', readingTime: '6 min read', featured: true,
    content: ['The strongest brands rarely ask to be decoded. They create a clear point of view, then repeat it with enough discipline that people can recognise it in a glance.', 'That clarity starts before the visual identity. It begins with deciding what the brand is here to make possible, who it is for, and what it is willing to leave out.', 'A useful identity makes good decisions easier. It gives teams a shared language for photography, film, content, digital experiences and every small expression in between.', 'The result is not a smaller brand. It is a brand with more room to move.'],
  },
  {
    slug: 'what-makes-a-visual-identity-feel-consistent', title: 'What Makes a Visual Identity Feel Consistent?', excerpt: 'Consistency is less about repeating the same elements and more about building a recognisable way of seeing.', category: 'Design', tags: ['Design', 'Identity'], image: images.architecture, imageAlt: 'Geometric contemporary building facade', author: 'BrandWorks', date: '2026-09-11', readingTime: '5 min read', content: ['A visual identity becomes coherent when its choices feel related, even when the applications are different.', 'That relationship comes from a small number of principles: how images are framed, how type is paced, how colour is used and how much space an idea is allowed to occupy.'] },
  {
    slug: 'the-role-of-photography-in-brand-perception', title: 'The Role of Photography in Brand Perception', excerpt: 'Photography is not the final layer of a brand. It is often the first evidence people believe.', category: 'Photography', tags: ['Photography', 'Production'], image: images.camera, imageAlt: 'Camera resting on a studio table', author: 'BrandWorks', date: '2026-09-04', readingTime: '4 min read', content: ['Images make a promise before a visitor reads a line of copy.', 'The most useful photography systems balance a distinctive point of view with enough flexibility to keep a brand alive across campaigns, social and digital.'] },
  {
    slug: 'seo-is-not-just-about-ranking', title: 'SEO Is Not Just About Ranking', excerpt: 'Search is a product experience: it connects the right question with the clearest useful answer.', category: 'SEO', tags: ['SEO', 'Digital'], image: images.editorial, imageAlt: 'Editorial desk with notebook and typography', author: 'BrandWorks', date: '2026-08-28', readingTime: '5 min read', content: ['Visibility is only the beginning. A useful search strategy makes a brand easier to understand at the exact moment someone is looking for it.', 'That means strong information architecture, helpful language and pages that respect the intent behind a query.'] },
  {
    slug: 'why-social-content-needs-a-point-of-view', title: 'Why Social Content Needs a Point of View', excerpt: 'A content calendar can organise output. It cannot create a reason to care.', category: 'Social Media', tags: ['Content', 'Culture'], image: images.film, imageAlt: 'Film set with cinema camera and soft light', author: 'BrandWorks', date: '2026-08-19', readingTime: '4 min read', content: ['The most memorable feeds are not the busiest. They are the ones where every post feels like it belongs to a living perspective.', 'Point of view gives a content system its rhythm, its boundaries and its confidence.'] },
  {
    slug: 'designing-digital-experiences-people-understand', title: 'Designing Digital Experiences People Actually Understand', excerpt: 'Good digital design makes the next useful action feel natural.', category: 'Digital', tags: ['Technology', 'Experience'], image: images.portrait, imageAlt: 'Minimal creative workspace with a large window', author: 'BrandWorks', date: '2026-08-12', readingTime: '6 min read', content: ['Clarity in a digital experience is felt in the moments between clicks.', 'When structure, language and interaction work together, a website becomes more than a surface. It becomes a confident guide.'] },
]

export const newsPosts: EditorialPost[] = [
  { slug: 'inside-a-recent-brandworks-production', title: 'Inside a Recent BrandWorks Production', excerpt: 'A look at the people, process and considered details behind a new campaign film.', category: 'Work', tags: ['Production', 'Film'], image: images.film, imageAlt: 'Cinema camera pointed toward a film set', author: 'BrandWorks', date: '2026-09-22', content: ['Great production is a shared act of attention. From the first treatment to the final grade, this project brought strategy, direction and craft into the same room.', 'The work moved from a clear central idea: make the product feel present, tactile and unmistakably human.'] },
  { slug: 'brandworks-expands-creative-production-capabilities', title: 'BrandWorks Expands Its Creative Production Capabilities', excerpt: 'New production resources help our team take more ideas from first frame to final delivery.', category: 'Announcements', tags: ['Studio', 'Production'], image: images.studio, imageAlt: 'BrandWorks creative studio interior', author: 'BrandWorks', date: '2026-09-08', content: ['BrandWorks is expanding its creative production capabilities across photography, film and content systems.', 'The move gives our partners a more connected path from strategy and creative direction through to production and distribution.'] },
  { slug: 'a-new-visual-identity-takes-shape', title: 'A New Visual Identity Takes Shape', excerpt: 'Our latest collaboration turns a complex story into a confident visual language.', category: 'Collaborations', tags: ['Identity', 'Work'], image: images.architecture, imageAlt: 'Abstract architectural lines and shadows', author: 'BrandWorks', date: '2026-08-26', content: ['This identity project began with a simple question: what should the audience feel before they know what they are looking at?', 'The answer became a system of measured typography, open space and images with a strong sense of place.'] },
  { slug: 'behind-the-scenes-of-our-latest-campaign', title: 'Behind the Scenes of Our Latest Campaign', excerpt: 'A quiet look at the decisions that made a busy campaign feel simple.', category: 'Campaigns', tags: ['Campaigns', 'Culture'], image: images.camera, imageAlt: 'Camera and lens ready for a campaign shoot', author: 'BrandWorks', date: '2026-08-09', content: ['Every campaign contains a hundred small decisions. The best ones are often the least visible: a pause, a crop, a line edited out.'] },
  { slug: 'brandworks-in-the-press', title: 'BrandWorks in the Press', excerpt: 'Selected coverage and conversations from across our creative practice.', category: 'Press', tags: ['Press', 'Studio'], image: images.editorial, imageAlt: 'Open magazine on an editorial desk', author: 'BrandWorks', date: '2026-07-28', content: ['We are grateful to see our work and our way of working included in conversations about modern brand building.'] },
]
